# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: deps:node:.
version: 2.1
jobs:
  build_and_run:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Build image
          command: docker build -t $DOCKERHUB_USERNAME/sample-node-js:0.1.$CIRCLE_BUILD_NUM .
      
      - run:
          name: Run the app with docker compose
          command: docker compose up -d --build

      - run:
          name: Install curl to test the app
          command: sudo apt install curl

      - run:
          name: Test if the app is running
          command: curl http://localhost:8080/

      - run:
          name: Push the image to the repo
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/sample-node-js:$TAG

workflows:
  example:
    jobs:
      - build_and_run